---
name: default
kind: pipeline
type: docker

steps:
  - name: composer
    image: composer
    volumes:
      - name: composer
        path: /composer
    environment:
      COMPOSER_HOME: /composer
    commands:
      - composer install --no-ansi --no-interaction --ignore-platform-reqs

  - name: static analysis
    image: d.xr.to/eater/php7.4rc6
    commands:
      - ./vendor/bin/phpstan analyse --no-ansi --no-interaction -l max -a vendor/autoload.php src
    depends_on:
      - composer

  - name: testing
    image: d.xr.to/eater/php7.4rc6
    commands:
      - ./vendor/bin/phpunit --colors=always
    depends_on:
      - composer

volumes:
  - name: composer
    host:
      path: /tank/var/composer-cache
---
kind: signature
hmac: f37f65151151bb234e48025637865312bcf2b099c6550775fdc0a2b5fba73887
